# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "migrate-ci" ]
  pull_request:
    branches: [ "migrate-ci" ]

jobs:
  build-and-test:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2
    - name: Select xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Build and run tests
      run: 
        xcodebuild clean build test -project "HungryNow.xcodeproj" -scheme "HungryNowTests" -destination "platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
 