# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "migrate-ci" ]
  pull_request:
    branches: [ "migrate-ci" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    strategy:
      matrix:
        xcode: [15.0]

    steps:
    - uses: actions/checkout@v3
    - name: Select xcode 
      uses: sudo xcode-select -switch /Applications/Xcode.app

    - name: Build and run tests
      run: xcodebuild clean build test -project "HungryNow.xcodeproj" -scheme "CI" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
 